---
namespace: middleware_automation
name: common
version: "2.0.0"
readme: README.md
authors:
  - Andrew Block <ablock@redhat.com>
  - Guido Grazioli <ggraziol@redhat.com>
description: Common utilities to support Ansible Middleware automation.
license_file: "LICENSE"
tags:
  - utilities
  - products
  - download
  - search
  - tools
  - runtimes
  - middleware
  - a4mw
dependencies: {}
repository: https://github.com/ansible-middleware/common
documentation: https://ansible-middleware.github.io/common
homepage: https://github.com/ansible-middleware/common
issues: https://github.com/ansible-middleware/common/issues
build_ignore:
  - .gitignore
  - .github
  - .ansible-lint
  - .yamllint
  - '*.tar.gz'
  - '*.zip'
  - molecule
  - changelogs
  - docs/_gh_include
  - docs/conf.py
  - docs/roles.rst.template
  - docs/requirements.yml
