---
- name: Download JWS 5.5 Documentation
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    client_id: ee77a54c-a8eb-4ced-a1a7-aba57cdcef4e
    client_secret: Eaa5rRFe7UM2xaGuWQtivNqbFgsiLvby
      #product_version: '7.10.1'
    product_version: '7.4'
    product_category: appplatform
      #product_category: core.service.rhsso
      #product_category: data.grid
      #prduct_category: jboss.amq.broker
      #product_type: DISTRIBUTION
    product_type: BUGFIX
      #producttype: SECURITY
  tasks:
    - name: Search EAP Product
      middleware_automation.common.product_search:
        client_id: "{{ client_id }}"
        client_secret: "{{ client_secret }}"
        product_version: "{{ product_version|default(omit) }}" 
        product_type: "{{ product_type|default(omit) }}"
        product_category: "{{ product_category|default(omit) }}"
          #product_id: 104526
      register: product_results

    - name: Filter install zipfile 
      ansible.builtin.set_fact:
        #filtered_products: "{{ product_results.results | json_query('[?title==join(`\" \"`,[name,version])]') | list }}"
        #filtered_products: "{{ product_results.results | selectattr('file_path', 'equalto', 'JBEAP-7.4.9/jboss-eap-7.4.9-patch.zip') }}"
        #filtered_products: "{{ product_results.results | selectattr('file_path', 'equalto', 'rhsso-7.4.1/rh-sso-7.4.1-patch.zip') }}"
        #filtered_products: "{{ product_results.results | map(attribute='file_path') | map('regex_replace','[^/]*/jboss-eap-([0-9.]*)-patch.zip','\\1' ) | list }}"
        #filtered_products: "{{ product_results.results | map(attribute='file_path') | select('match', '^[^/]*/jboss-eap-.*[0-9]*[.][0-9]*[.][0-9]*.*$') | map('regex_replace','[^/]*/jboss-eap-([0-9]*[.][0-9]*[.][0-9]*)-.*','\\1' ) | list | unique }}"
        filtered_versions: "{{ product_results.results | map(attribute='file_path') | select('match', '^[^/]*/jboss-eap-.*[0-9]*[.][0-9]*[.][0-9]*.*$') | map('regex_replace','[^/]*/jboss-eap-([0-9]*[.][0-9]*[.][0-9]*)-.*','\\1' ) | list | unique }}"

    - name: Determine latest version
      set_fact:
         eap_latest_version: "{{ filtered_versions | community.general.version_sort | last }}"

    - name: Filter results
      ansible.builtin.set_fact:
        filtered_products: "{{ product_results.results | selectattr('file_path', 'match', '^[^/]*/jboss-eap-' + eap_latest_version + '-patch.zip$') | list }}"

    - name: Fail if more than 1 product exists in filtered list
      ansible.builtin.debug:
        var: filtered_products

