---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '18 6 * * *'

jobs:
  ci:
    uses: ansible-middleware/github-actions/.github/workflows/ci.yml@main
    secrets: inherit
    with:
      fqcn: 'middleware_automation/common'
      molecule_tests: >-
        [ "prod_eap", "stage_eap" ]
