---
name: Documentation
on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

env:
  COLORTERM: 'yes'
  TERM: 'xterm-256color'
  PYTEST_ADDOPTS: '--color=yes'

jobs:
  docs:
    uses: ansible-middleware/github-actions/.github/workflows/docs.yml@main
    secrets: inherit
    with:
      fqcn: 'middleware_automation/common'
      collection_fqcn: 'middleware_automation.common'
